#!/bin/sh

echo "=== [DevSecOps] Εκκίνηση Στατικού Ελέγχου Κώδικα με Semgrep (Pre-push) ==="

PWD_WIN=$(pwd -W 2>/dev/null || pwd)

MSYS_NO_PATHCONV=1 docker run --rm -v "${PWD_WIN}:/src" returntocorp/semgrep semgrep scan --config=p/csharp --error

RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo -e "\nSemgrep detected critical vulnerabilities !\nPush blocked. Please fix the security issues to continue."
    exit 1
else
    echo -e "\nCode passed Semgrep check. Push allowed!"
    exit 0
fi