#!/bin/sh

echo "===== Εκκίνηση Στατικού Ελέγχου με TruffleHog ====="

PWD_WIN=$(pwd -W 2>/dev/null || pwd)

MSYS_NO_PATHCONV=1 docker run --rm -v "${PWD_WIN}:/pwd" trufflesecurity/trufflehog:latest filesystem /pwd --fail

RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo -e "\nSecrets detected!\nCommit blocked. Please remove them to continue."
    exit 1
else
    echo -e "\nNo secrets found. Commit allowed!"
    exit 0
fi